### ISSUE TITLE
error on RPi Raspbian box

### ISSUE THREAD

**Issue by EMCP** [pwnieexpress/blue_hydra#118]
ran through installation instructions, went to execute and saw the following : 

disclaimer, this box only has an Ubertooth attached to it, and no bluetooth dongle.  If that's the cause for this error feel free to close 

```
pi@raspberrypi:~/Dev/git/pwnieexpress/blue_hydra $ sudo bundle exec ./bin/blue_hydra
/usr/lib/ruby/2.1.0/json/common.rb:155:in `encode': "\xC3" on US-ASCII (Encoding::InvalidByteSequenceError)
	from /usr/lib/ruby/2.1.0/json/common.rb:155:in `initialize'
	from /usr/lib/ruby/2.1.0/json/common.rb:155:in `new'
	from /usr/lib/ruby/2.1.0/json/common.rb:155:in `parse'
	from /var/lib/gems/2.1.0/gems/louis-2.0.7/lib/louis.rb:17:in `<module:Louis>'
	from /var/lib/gems/2.1.0/gems/louis-2.0.7/lib/louis.rb:7:in `<top (required)>'
	from /home/pi/Dev/git/pwnieexpress/blue_hydra/lib/blue_hydra.rb:16:in `require'
	from /home/pi/Dev/git/pwnieexpress/blue_hydra/lib/blue_hydra.rb:16:in `<top (required)>'
	from ./bin/blue_hydra:48:in `require'
	from ./bin/blue_hydra:48:in `<main>'

```

**Comment by EMCP** [comment]
just read the end of the README.md *facepalm* closing
