### ISSUE TITLE
Stops working and fails to restart

### ISSUE THREAD

**Issue by MitchSUEW** [pwnieexpress/blue_hydra#125]
After starting it with:
sudo ./bin/blue_hydra
it suddenly stops without an error message. When I try starting again the error is:
/home/pi/blue_hydra/lib/blue_hydra/runner.rb:232:in `block in stop': undefined method `status' for nil:NilClass (NoMethodError)
	from /home/pi/blue_hydra/lib/blue_hydra/runner.rb:238:in `stop'
	from ./bin/blue_hydra:193:in `<main>'

Any ideas?
Thanks,
Michael

**Comment by dallaswinger** [comment]
It appears the result thread did not start; this error is the result of BlueHydra trying to gracefully shutdown, but throwing exceptions for no result thread while doing so.

Do you have a more complete BlueHydra log? That could help determine the root cause.

Thanks,
- Dallas
