### ISSUE TITLE
Chunker thread no implicit conversion of nil into String Error

### ISSUE THREAD

**Issue by Marineflieger** [pwnieexpress/blue_hydra#135]
Hardware:
-  Raspberry pi 3b+ 
-  LM-1010 Bluetooth v4.0 Dual Mode Long Range USB Adapter

OS:
Linux kali 4.19.55-Re4son-v7+ #1 SMP Sun Jun 30 15:32:25 AEST 2019 armv7l

_As blue_hydra wasn't detecting anything, I looked into the logfile, which reported this Error_:

```
I, [2019-08-19T14:39:39.882053 #1534]  INFO -- : BlueHydra Starting...
I, [2019-08-19T14:39:39.886398 #1534]  INFO -- : No devices found in DB, starting clean.
I, [2019-08-19T14:39:39.886710 #1534]  INFO -- : Result thread starting
I, [2019-08-19T14:39:39.887037 #1534]  INFO -- : Parser thread starting
I, [2019-08-19T14:39:39.887357 #1534]  INFO -- : Chunker thread starting
I, [2019-08-19T14:39:39.903892 #1534]  INFO -- : Btmon thread starting
I, [2019-08-19T14:39:39.904275 #1534]  INFO -- : Discovery thread starting
I, [2019-08-19T14:39:39.904490 #1534]  INFO -- : Command Line UI thread starting
I, [2019-08-19T14:39:39.903505 #1534]  INFO -- : Pulse sync starting...
I, [2019-08-19T14:39:39.932094 #1534]  INFO -- : 0 host sync complete
I, [2019-08-19T14:39:39.940797 #1534]  INFO -- : ...Pulse sync complete
E, [2019-08-19T14:39:39.941537 #1534] ERROR -- : Chunker thread no implicit conversion of nil into String
E, [2019-08-19T14:39:39.945371 #1534] ERROR -- : /usr/lib/ruby/2.5.0/time.rb:367:in `_parse'
E, [2019-08-19T14:39:39.945531 #1534] ERROR -- : /usr/lib/ruby/2.5.0/time.rb:367:in `parse'
E, [2019-08-19T14:39:39.945608 #1534] ERROR -- : /root/blue_hydra/lib/blue_hydra/chunker.rb:71:in `chunk_it_up'
E, [2019-08-19T14:39:39.945684 #1534] ERROR -- : /root/blue_hydra/lib/blue_hydra/runner.rb:703:in `block (2 levels) in start_chunker_thread'
E, [2019-08-19T14:39:39.945760 #1534] ERROR -- : /root/blue_hydra/lib/blue_hydra/runner.rb:696:in `loop'
E, [2019-08-19T14:39:39.945834 #1534] ERROR -- : /root/blue_hydra/lib/blue_hydra/runner.rb:696:in `block in start_chunker_thread'
W, [2019-08-19T14:39:39.945942 #1534]  WARN -- : Restarting Chunker...
```

_And it keeps spinning in circles forever..
I would be very happy about any tip, thank you_

**Comment by Marineflieger** [comment]
`E, [2019-08-19T14:39:39.945371 #1534] ERROR -- : /usr/lib/ruby/2.5.0/time.rb:367:in `_parse'`

_So, has the problem to do with ruby?_
