### ISSUE TITLE
UTF-8 Encoding and Ruby - ERROR: "\xC3" on US-ASCII

### ISSUE THREAD

**Issue by llazzaro** [pwnieexpress/blue_hydra#65]
While running blue_hydra I got this error:
I'm not sure but it seems that a device is using a special char.
```
E, [2016-08-25T20:01:19.983800 #4475] ERROR -- : Parser thread "\xC3" on US-ASCII
E, [2016-08-25T20:01:19.985850 #4475] ERROR -- : /usr/lib/ruby/2.1.0/json/common.rb:155:in `encode'
E, [2016-08-25T20:01:19.986395 #4475] ERROR -- : /usr/lib/ruby/2.1.0/json/common.rb:155:in `initialize'
E, [2016-08-25T20:01:19.987932 #4475] ERROR -- : /usr/lib/ruby/2.1.0/json/common.rb:155:in `new'
E, [2016-08-25T20:01:19.989472 #4475] ERROR -- : /usr/lib/ruby/2.1.0/json/common.rb:155:in `parse'
E, [2016-08-25T20:01:19.991021 #4475] ERROR -- : /var/lib/gems/2.1.0/gems/louis-2.0.4/lib/louis.rb:18:in `lookup_table'
E, [2016-08-25T20:01:19.994272 #4475] ERROR -- : /var/lib/gems/2.1.0/gems/louis-2.0.4/lib/louis.rb:37:in `lookup'
E, [2016-08-25T20:01:19.994707 #4475] ERROR -- : /home/pi/blue_hydra/lib/blue_hydra/cli_user_interface_tracker.rb:159:in `update_cui_status'
E, [2016-08-25T20:01:19.995039 #4475] ERROR -- : /home/pi/blue_hydra/lib/blue_hydra/runner.rb:580:in `block in start_parser_thread'
E, [2016-08-25T20:01:22.787320 #4475] ERROR -- : Thread failure: parser_thread

```

**Comment by ZeroChaos-** [comment]
In my testing this happens when the system running blue_hydra is improperly configured to support utf-8. That said, patches welcome if there is a way to fix it on our end.

**Comment by llazzaro** [comment]
Thank you. I manage to solve with this commands

sudo locale-gen  en_US.UTF-8 
sudo locale-gen  en en_US  en_US.UTF-8
sudo dpkg-reconfigure locales
export LC_ALL = "en_US"
