### ISSUE TITLE
test-discovery script error

### ISSUE THREAD

**Issue by pcgeller** [pwnieexpress/blue_hydra#85]
I'm running BH on Raspian Jessie on a rPi3 using the Sena bluetooth dongle.  Blue Hydra tends to run fine but I keep getting an error starting the test-discovery script.  It says the network device is down but when I run hciconfig or ifconfig both the dongle and network devices are shown as up and running.  

Also, the error below frequently shows up in the logs with different addresses:

``` shell
E, [2016-09-28T06:46:15.366533 #2267] ERROR -- : Error with info command... {:command=>:info, :address=>"XX:XX:XX:XX:XX:XX"}
```

Any help on diagnosing whats going  would be greatly appreciated as this this error will cause the program to freeze up.

I'm trying hard to not earn myself a second snarky edit to the readme :)

The full output of the log is :

``` shell
I, [2016-09-28T06:42:39.340318 #2267]  INFO -- : BlueHydra Starting...
I, [2016-09-28T06:42:39.340636 #2267]  INFO -- : Runner starting with 'btmon -T -i hci0' ...
I, [2016-09-28T06:42:39.364185 #2267]  INFO -- : Marking older devices as 'offline'...
I, [2016-09-28T06:42:39.422177 #2267]  INFO -- : Btmon thread starting
I, [2016-09-28T06:42:39.422686 #2267]  INFO -- : Discovery thread starting
I, [2016-09-28T06:42:39.429876 #2267]  INFO -- : Chunker thread starting
I, [2016-09-28T06:42:39.436589 #2267]  INFO -- : Parser thread starting
I, [2016-09-28T06:42:39.437284 #2267]  INFO -- : Result thread starting
I, [2016-09-28T06:42:39.439997 #2267]  INFO -- : Command Line UI thread starting
E, [2016-09-28T06:43:11.762659 #2267] ERROR -- : Error with test-discovery script..
E, [2016-09-28T06:43:11.762981 #2267] ERROR -- : Traceback (most recent call last):
E, [2016-09-28T06:43:11.763089 #2267] ERROR -- :   File "/home/pi/bigTooth/blue_hydra/bin/test-discovery", line 43, in <module>
E, [2016-09-28T06:43:11.763181 #2267] ERROR -- :     adapter.StopDiscovery()
E, [2016-09-28T06:43:11.763271 #2267] ERROR -- :   File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
E, [2016-09-28T06:43:11.763372 #2267] ERROR -- :     **keywords)
E, [2016-09-28T06:43:11.763467 #2267] ERROR -- :   File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
E, [2016-09-28T06:43:11.763566 #2267] ERROR -- :     message, timeout)
E, [2016-09-28T06:43:11.763655 #2267] ERROR -- : dbus.exceptions.DBusException: org.freedesktop.DBus.Error.ServiceUnknown: The name :1.2 was not provided by any .service files
E, [2016-09-28T06:46:04.038186 #2267] ERROR -- : Error with test-discovery script..
E, [2016-09-28T06:46:04.038482 #2267] ERROR -- : Traceback (most recent call last):
E, [2016-09-28T06:46:04.038606 #2267] ERROR -- :   File "/home/pi/bigTooth/blue_hydra/bin/test-discovery", line 43, in <module>
E, [2016-09-28T06:46:04.038711 #2267] ERROR -- :     adapter.StopDiscovery()
E, [2016-09-28T06:46:04.038813 #2267] ERROR -- :   File "/usr/lib/python2.7/dist-packages/dbus/proxies.py", line 145, in __call__
E, [2016-09-28T06:46:04.038908 #2267] ERROR -- :     **keywords)
E, [2016-09-28T06:46:04.039008 #2267] ERROR -- :   File "/usr/lib/python2.7/dist-packages/dbus/connection.py", line 651, in call_blocking
E, [2016-09-28T06:46:04.039102 #2267] ERROR -- :     message, timeout)
E, [2016-09-28T06:46:04.039228 #2267] ERROR -- : dbus.exceptions.DBusException: org.bluez.Error.Failed: No discovery started
E, [2016-09-28T06:46:14.351301 #2267] ERROR -- : Error with hciconfig hci0 reset..
E, [2016-09-28T06:46:14.353346 #2267] ERROR -- : Can't init device hci0: No such device (19)
E, [2016-09-28T06:46:15.366533 #2267] ERROR -- : Error with info command... {:command=>:info, :address=>"08:74:02:16:E8:FE"}
E, [2016-09-28T06:46:15.366831 #2267] ERROR -- : Invalid device: Network is down

```

**Comment by ZeroChaos-** [comment]
Is this still occuring with the latest code?  There have been a few attempts to better handle error states which may fix this.  mind you, your bluetooth card and/or dbus going out to lunch may still happen, but BlueHydra should deal with it more usefully.

**Comment by pcgeller** [comment]
I haven't seen this in more recent updates.  Still a great tool - major
props.
