### ISSUE TITLE
Btmon log not being saved

### ISSUE THREAD

**Issue by ChristianHL** [pwnieexpress/blue_hydra#99]
Hi,

When BH is closed, it will sometimes fail to save the output to the btmon log file. When closing BH it prints:
```
zlib(finalizer): Zlib::GzipWriter object must be closed explicitly.
zlib(finalizer): the stream state was inconsistent.
```

The log file will end up being only 10 bytes long.

The BH log says the following:
```
D, [2017-03-14T16:26:28.070151 #2029] DEBUG -- : Executing Command: hciconfig hci0 reset
D, [2017-03-14T16:26:29.206421 #2029] DEBUG -- : Executing Command: /home/pi/blue_hydra-1.8.0/bin/test-discovery -i hci0
I, [2017-03-14T16:26:46.367751 #2029]  INFO -- : Runner stopped. Exiting after clearing queue...
I, [2017-03-14T16:26:46.368102 #2029]  INFO -- : Queue clear! Exiting.
W, [2017-03-14T16:26:46.380193 #2029]  WARN -- : GOODBYE! ^_^
E, [2017-03-14T16:26:46.381145 #2029] ERROR -- : Btmon thread data error
E, [2017-03-14T16:26:46.381405 #2029] ERROR -- : /home/pi/blue_hydra-1.8.0/lib/blue_hydra/btmon_handler.rb:36:in `close'
E, [2017-03-14T16:26:46.381521 #2029] ERROR -- : /home/pi/blue_hydra-1.8.0/lib/blue_hydra/btmon_handler.rb:36:in `ensure in initialize'
E, [2017-03-14T16:26:46.381621 #2029] ERROR -- : /home/pi/blue_hydra-1.8.0/lib/blue_hydra/btmon_handler.rb:37:in `initialize'
E, [2017-03-14T16:26:46.381717 #2029] ERROR -- : /home/pi/blue_hydra-1.8.0/lib/blue_hydra/runner.rb:251:in `new'
E, [2017-03-14T16:26:46.381810 #2029] ERROR -- : /home/pi/blue_hydra-1.8.0/lib/blue_hydra/runner.rb:251:in `block in start_btmon_thread'
```
This does not happen all the time, I have not been able to determine if there's a pattern, but it seems to be more likely to happen once BH has been running for more than a couple of minutes.

**Comment by ZeroChaos-** [comment]
Just so it doesn't look like I'm ignoring this forever.... yes, I've seen that too, and no, I have no idea why.  It doesn't seem to be doing it anymore, there have been like 5 passes on proper thread cleanup so hopefully this is gone.
